// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.15.1")]
[assembly: AssemblyFileVersionAttribute("0.15.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "0.15.1";
        internal const System.String AssemblyFileVersion = "0.15.1";
    }
}
