// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.12.0")]
[assembly: AssemblyFileVersionAttribute("0.12.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.12.0";
    }
}
