// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.9.1")]
[assembly: AssemblyFileVersionAttribute("0.9.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.9.1";
    }
}
