// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("0.15.0")>]
[<assembly: AssemblyFileVersionAttribute("0.15.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "0.15.0"
    let [<Literal>] AssemblyFileVersion = "0.15.0"
