// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.2.3")]
[assembly: AssemblyFileVersionAttribute("0.2.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.3";
    }
}
