// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.2.4")]
[assembly: AssemblyFileVersionAttribute("0.2.4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.4";
    }
}
